[package]
name = "qcm_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
prost = "0.13"
futures-util = "0.3.30"
tokio-tungstenite = "0.26"
reqwest = { version = "0.12", features = ["json"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
tokio = { version = "1", features = ["full"] }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
openssl = "0.10"
base64 = "0.22"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }