[package]
name = "qcm_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
prost = "0.13"
futures-util = "0.3.30"
tokio-tungstenite = "0.26"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }