[package]
name = "qcm-backend"
authors = ["hypengw <hypengwip@gmail.com>"]
version.workspace = true
edition.workspace = true

[dependencies]
qcm-core = { path = "../core" }
serde = { version = "1.0" }
serde_json = "1.0"

once_cell = "1"
migration = { path = "./migration" }
sea-orm = { version = "1.1" }
sqlx = "0.8"
clap = { version = "4.5", features = ["derive", "env"] }
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
prost = "0.13"
prost-types = "0.13"
futures-util = "0.3.30"
tokio-tungstenite = "0.26"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.9"

qcm-plugins = { path = "../plugin" }

[build-dependencies]
prost-build = "0.13"
